name: Render Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-ciuhorh5rnuhcntum0o0   # Replace with your actual service ID
          retries: 20
          wait: 16000
          sleep: 30000