name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint tests
        run: npm run lint

      - name: Notify Discord on ESLint Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: "ESLint Failed, files need to be fixed before releasing."
        node-version: 16  

      - name: Trigger deployment
        run: curl "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      - name: Notify Discord on Success
        uses: rjstone/discord-webhook-notify@v1
        if: success() 
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: info
          details: "The deployment was successful."
        node-version: 16  

      - name: Notify Discord on Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure() 
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: "The deployment failed."
        node-version: 16  

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      !contains(github.event.head_commit.message, '#skip')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: false
          BUMP: patch

      - name: Notify Discord on Success
        uses: rjstone/discord-webhook-notify@v1
        if: success() 
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: info
          details: "The deployment was successful."
        node-version: 16  

      - name: Notify Discord on Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure() 
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: "The deployment failed."
        node-version: 16  
